application:
  title: App for book library
  version: 1.0

spring:
  data:
    mongodb:
      port: 0
      database: library
  shell:
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - com.ferick.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local