application:
  title: App for skynet laboratory
  version: 1.0

spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

scheduler-thread-pool:
  threadNumber: 3

storage:
  capacity: 50